repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: register-all-servers
      name: Register all MCP servers
      entry: bash -c 'cd $(git rev-parse --show-toplevel) && just register-all-servers'
      language: system
      pass_filenames: false
