# fly.toml app configuration file generated for learning-quiet-violet-8758 on 2025-03-08T14:50:42-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'learning-quiet-violet-8758'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
